name: Shaun Tinney
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Shaun Tinney is a professional creative person
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-18889208-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#0d0c14'
    - '#8c9bb3'
    - '#394860'
    - '#1378bb'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
