name: Shaun Tinney
favicon: null
layout_spectrum: 0.6803053780458868
typography_spectrum: 0.1826393899973482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.43238063575699925
  lightness: 0.8036133258137852
  saturation: 0.37874831701628864
  rhythmicContrast: 0.9109076922759414
purpose: []
